### ISSUE TITLE
Basic Functionality

### ISSUE THREAD

**Issue by Ayman-Shahrour** [tony-xlh/APEX-Dynamic-Web-TWAIN#2]
Hi,
I have installed the apex plugin and all the available functionalities are working fine except the insert, always it shows "The image has not been uploaded" message. it seems there is a missing in the requirements as you mentioned in  [requirements.txt] 

could you please elaborate more how to achieve the required setup  and on which server should be done (DB /ORDS or other?)
 
The second thing could you please guide me how achieve the basic functionality without using the dialog that appears when I press 
on ShowScanner button. and to be more clear how do I achieves the exact functionalities as shown in the attached picture in addition 
to save the scanned images as one pdf file.

![DWT](https://github.com/tony-xlh/APEX-Dynamic-Web-TWAIN/assets/121610355/0f3a0028-111e-4500-bd14-9a489f4696ce)

Thank you very much.
Ayman

**Comment by xulihang** [comment]
1. You have to upload the image to an HTTP server and then you can insert its URL into the database. Check out the readme for details.
2. If you need to modify the default interface and add functions. You have to modify script.js by yourself according to Web TWAIN's docs and then update the corresponding files in the plugin.

**Comment by Ayman-Shahrour** [comment]
I have modified the default interface to suit our requirements,   
Thank you very much for the guidance.
